app = "crinj"
primary_region = "cdg"
swap_size_mb = 512



[env]
BOT_ACTIVITY = "Domestic na Kanojo"
BOT_ACTIVITY_TYPE = "WATCHING"
BOT_ACTIVITY_URL= "https://kaido.to/watch/domestic-girlfriend-4219?ep=37054"
BOT_STATUS = "dnd"
CACHE_LIMIT = "128MB"
DATA_DIR = "./data"
ENABLE_SPONSORBLOCK = true
SPONSORBLOCK_TIMEOUT = 5

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8080
min_machines_running = 0
processes = [ "app" ]

[vm]
size = "shared-cpu-1x"
memory = "700mb"
