app = "crinj"
primary_region = "cdg"

[env]
BOT_ACTIVITY = "Domestic na Kanojo"
BOT_ACTIVITY_TYPE = "WATCHING"
BOT_STATUS = "dnd"
CACHE_LIMIT = "128MB"
DATA_DIR = "./data"
ENABLE_SPONSORBLOCK = true

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]
